SELECT FTH.TRANSACTION_HEADER_ID "TRANSACTION NUMBER"
,       FTH.TRANSACTION_TYPE_CODE "TRANSACTION TYPE"
,       TO_CHAR(FTH.TRANSACTION_DATE_ENTERED,'dd/mm/yy') "TRANSACTION DATE"
,       FTH.TRANSACTION_NAME "COMMENTS"
,       TO_CHAR(FTH.AMORTIZATION_START_DATE,'dd/mm/yy') "AMORTIZATION START DATE"
,       FAB.ASSET_NUMBER "ASSET NUMBER"
,       FBC.AMORTIZE_FLAG "AMORTIZE"
-- ,       FDP.PERIOD_NAME "PERIOD NAME"
,       FAT.DESCRIPTION "DESCRIPTION"


,       FR.COST "COST"
,       FR.REVAL_RESERVE "REVALUATION RESERVE"
,       FR.LIFE_IN_MONTHS "LIFE IN MONTHS"
,       FR.REVAL_METHOD "REVALUATION METHOD"
,       FR.REVAL_GAIN_LOSS "REVALUATION GAIN OR LOSS"
,       FR.FAIR_MARKET_VALUE "FAIR VALUE"


FROM FA_TRANSACTION_HEADERS FTH
,   FA_ADDITIONS_B FAB
,   FA_ADDITIONS_TL FAT
,   FA_BOOK_CONTROLS FBC
-- ,   FA_DEPRN_PERIODS FDP
-- ,   FA_BOOKS FB
,   FA_REVALUATIONS FR

WHERE FTH.ASSET_ID = FAB.ASSET_ID
AND     FTH.TRANSACTION_HEADER_ID = '92045'
AND     FBC.BOOK_TYPE_CODE = FTH.BOOK_TYPE_CODE 
-- AND     FDP.BOOK_TYPE_CODE = FB.BOOK_TYPE_CODE
-- AND     FB.TRANSACTION_HEADER_ID_IN = FTH.TRANSACTION_HEADER_ID
AND     FAT.ASSET_ID = FAB.ASSET_ID
-- AND     FAB.ASSET_ID = FB.ASSET_ID
-- AND     FDP.BOOK_TYPE_CODE = FB.BOOK_TYPE_CODE
AND     FR.TRANSACTION_HEADER_ID = FTH.TRANSACTION_HEADER_ID



